### ISSUE TITLE
FSP Design Docs

### ISSUE THREAD

**Issue by mwmadsen67** [cubeydice/dupecord#1]
Hi Queen, here is a checklist for going through your docs. I'll go through what you have and leave comments underneath. 

---

# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

---

# Feature List

- [x] Should have 7 Features.
    - [x] 3 of those are User Auth, render.io, and Production README.
    - [x] The other 4 are from the [Feature/MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each feature
- [x] Correctly formatted
    - [x] features are listed in an ordered list
    - [x] Each feature is broken down into bullet points

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
    
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by mwmadsen67** [comment]
Hi Queen, excellent work on your docs! Here are some comments:

**Feature List:**
* After user auth, I would recommend working on servers and channels first, since your messages are going to belong to channels, and channels will have to belong to servers. Technically these are also two separate feature since they're different models.
* I would not recommend some of the functionalities you're aiming for on the servers, i.e. custom server names, voice channels, permissions, moderation, etc. It would likely take too long when finishing messages will be a priority.
* The focus with messaging will also be on the basic CRUD, while emoji reactions, markdown, search, and especially image sharing could be bonus features.
* That would make the order 1. servers 2. channels 3. messages 4. notifications
* DMs or friends is an alternative to notifications if you're interested.

**Schema:**
* users won't belong to a server, since they don't have any foreign keys.
* servers and channels look good
* I would recommend making messages polymorphic if you plan on having DMs, so that a message could either be in a channel or in a DM.
* I'm not sure about the current DM table, since to me it should be connecting from one person to another, rather than a channel, but maybe you can explain to me what the planned implementation is there.
* user_server is good
* friends needs  to have two friend ids, like the person friending and the other person being friended, and then typically also a column for status, that states whether its pending or theyre friends.

Ill write comments on sample state and routes next.,

**Comment by mwmadsen67** [comment]
**Sample State:**
* The different slices of state should be in curly braces, not arrays
* missing a session slice of state
* each record should be accessible by its id as a key
* keys should be in camel case
* you should check out the example to see what we're looking for here

**Backend Routes:**
* the wildcards should be :id, not :userId or :serverId
* backend routes should be in snake case
* post users does not need a wildcard
* the only server membership routes you need are post and delete, and they dont need any nesting
  * ex: `POST /api/user_servers` - create a new server member
* Probably wont need a channel index, as you should end up fetching all channels for a server as part of a server show request
* dont need to nest messages under channels or direct messages, messages can have their own backend routes


**Frontend Routes:**
* Right now, your frontend routes are kind of looking like backend routes, so I'm not going to nitpick. I recommend going to discord on the browser and just looking at the url as you navigate around the website. That will give you an idea of what components show up depending on the different urls. The point behind this design doc is to plan out which components get rendered depending on the URL. 
* Also, don't worry about password forgetting and resetting, any settings, and other miscellaneous parts of the app. In 2 weeks we should only focus on the planned specific features.

**Comment by cubeydice** [comment]
Hi Mike! I've made updates to the wiki per your comments and our conversation yesterday. 

Some specific points: 
**Feature List**
-  Feature list has been trimmed and adjusted to include the following: 
>  1. Hosting, 2. User Auth, 3. Servers, 4. Channels, 5. Real-time Messaging, 6. Friends, 7. Production README.md
- Timelines added
- Feature details now more specific on CRUD elements
- Not listed, but potential features to be added if time: reactions, emojis, image sharing, markdown

**Schema**
Majorly updated after our conversation yesterday. Below are points of particular interest:

_Users_
- Status is included but unused for now. Intention is to use it for online availability in a future update.

_General Relationships_
>< indicates a has_many relationship
-- indicates as has one relationship 
- `users` >--`user_servers`--< `servers` --< `channels` --< `messages`
- `users` >--< `friends` -- `DMs` --< `messages`
- `messages` are now polymorphic for `channels` and `DMs`

_Friends_
- `friends` has been updated to have 2 foreign keys for the `users` table:  `friendee_id` and `friender_id`
- The above change is to accommodate a friendship status in the `friends` table: "Friends", "Pending", "Blocked"
- Each friendship has one direct message, which functions as a private channel for two friends to share messages.
- In the future, may consider adding multi-friend chats

**Sample State**
Apologies for the formatting, I believe the sample state was out of date from my latest local version and should have proper formatting now. HOWEVER, made new changes based on the change in schema above. Some optional items are not currently reflected in the schema. 
- `users`: Password digest and session token are not reflected in the sample state

**Comment by cubeydice** [comment]
**Backend Routes**
- Mostly trimmed this one down, especially as per our convo that many details may need to be fetched on render for a single page (e.g. a server should always return channels and members)
- Question: How would you recommend that I create a route for removing a member from a server (whether oneself or another member)? Right now, my route isn't flat, as I need the params for the user_id of the person to be removed and the specific server_id of the server they will be removed from.

**Frontend Routes**
Greatly parsed down and reduced. Most of the previous details will be components either displayed at all times (e.g. sidebar) or will exist as modals.

**Comment by mwmadsen67** [comment]
Deleting a member from a server should just be `DELETE api/user_servers/:id` 

The id could be something prefetched when that component is loaded

**Comment by cubeydice** [comment]
I see, I can possibly pass it in as a prop. Updated! (Also updated the route to have user_servers pluralized)
