### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by cubeydice** [cubeydice/dupecord#2]
Deployed site: [dupecord](https://dupecord.onrender.com/)
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by mwmadsen67** [comment]
Hi Queen, I just went through your live site and the site kind of breaks if I try to create a new user with invalid info.

Otherwise auth is great 👍

**Comment by cubeydice** [comment]
Fixed! It should have proper error handling now. I also fixed an issue with logging out where state was persisting after sign out.
